[Setup]
; App Information
AppName=Move-It
AppVersion=1.0.3
AppPublisher=Move-It
AppPublisherURL=https://move-it.app

; Default Installation Folder (C:\Program Files\Move-It)
DefaultDirName={autopf}\Move-It

; Start Menu Folder Name
DefaultGroupName=Move-It

; Output settings for the generated installer
OutputDir=dist_installer
OutputBaseFilename=Move-It_Setup_v1.0.3
Compression=lzma2/ultra64
SolidCompression=yes

; Use the icon for the installer itself
SetupIconFile=icon.ico

; Ask for administrative privileges to install to Program Files
PrivilegesRequired=admin

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
; Copy the main standalone executable generated by PyInstaller
Source: "dist\Move-It\Move-It.exe"; DestDir: "{app}"; Flags: ignoreversion
; Copy the internal folder and all other dependencies PyInstaller created
Source: "dist\Move-It\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; Copy the icon file so shortcuts can reference it
Source: "icon.ico"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
; Create Start Menu Shortcut with icon
Name: "{group}\Move-It"; Filename: "{app}\Move-It.exe"; IconFilename: "{app}\icon.ico"
; Create Start Menu Uninstall Shortcut
Name: "{group}\{cm:UninstallProgram,Move-It}"; Filename: "{uninstallexe}"
; Create Desktop Shortcut with icon (if user checked the box)
Name: "{autodesktop}\Move-It"; Filename: "{app}\Move-It.exe"; IconFilename: "{app}\icon.ico"; Tasks: desktopicon

[Run]
; Launch the app automatically after installation finishes
Filename: "{app}\Move-It.exe"; Description: "{cm:LaunchProgram,Move-It}"; Flags: nowait postinstall skipifsilent
